### PR TITLE
added zipping function for log files

### PR DESCRIPTION
**Pull request by JasonLing95**
zip all log files and upload a tar file instead

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_cgppindel/3)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_cgppindel/3)* status: all files reviewed, 1 unresolved discussion (waiting on @JasonLing95)

___
*[src/cgppindel.sh, line 76 at r1](https://reviewable.io/reviews/eastgenomics/eggd_cgppindel/3#-MpBUDczEq5BBZ9dj87t:-MpBUDczEq5BBZ9dj87u:bn2w4q6) ([raw file](https://github.com/eastgenomics/eggd_cgppindel/blob/fe1c153ac936eb34cd3496cdd931d80ae9189a7e/src/cgppindel.sh#L76)):*
> ```Shell
> 
>     # Upload output files
>     dx-upload-all-outputs
> ```

could you add `--parallel` to the `dx-upload-all-outputs` to allow uploading in parallel: https://documentation.dnanexus.com/user/helpstrings-of-sdk-command-line-utilities#dx-upload-all-outputs

**Comment by JasonLing95** [comment]
___
*[src/cgppindel.sh, line 76 at r1](https://reviewable.io/reviews/eastgenomics/eggd_cgppindel/3#-MpBUDczEq5BBZ9dj87t:-MpBrk9v-bPcmOhyQ-EJ:b-62w1ik) ([raw file](https://github.com/eastgenomics/eggd_cgppindel/blob/fe1c153ac936eb34cd3496cdd931d80ae9189a7e/src/cgppindel.sh#L76)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

could you add `--parallel` to the `dx-upload-all-outputs` to allow uploading in parallel: https://documentation.dnanexus.com/user/helpstrings-of-sdk-command-line-utilities#dx-upload-all-outputs
</blockquote></details>

Added. Tested working 12:57 23/11/2021

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_cgppindel/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Review by jethror1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_cgppindel/3#-:-MpCDGlmCctweh0oB85G:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Pull request merged**
